services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.upturn.com.bd
      - OVERWRITECONDADDR=^172\..*$
      - TRUSTED_PROXIES=172.16.0.0/12 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 104.16.0.0/13 104.24.0.0/14 172.64.0.0/13 131.0.72.0/22
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice
      - onlyoffice_cache:/var/lib/onlyoffice
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

  openproject-db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=${OPENPROJECT_DB_PASSWORD}
      - POSTGRES_DB=openproject
      - POSTGRES_USER=openproject
    volumes:
      - openproject_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openproject"]
      interval: 10s
      timeout: 5s
      retries: 5

  openproject-cache:
    image: memcached:1.6-alpine
    restart: always
    command: memcached -m 512m

  openproject:
    image: openproject/community:13
    restart: always
    ports:
      - 8082:80
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=${OPENPROJECT_SECRET_KEY_BASE}
      - OPENPROJECT_HOST__NAME=${OPENPROJECT_DOMAIN_NAME}:8082
      - OPENPROJECT_HTTPS=false
      - DATABASE_URL=postgresql://openproject:${OPENPROJECT_DB_PASSWORD}@openproject-db/openproject?pool=20&encoding=unicode&reconnect=true
      - RAILS_CACHE_STORE=memcache
      - OPENPROJECT_CACHE__MEMCACHE__SERVER=openproject-cache:11211
      - OPENPROJECT_RAILS__RELATIVE__URL__ROOT=""
      - RAILS_MIN_THREADS=4
      - RAILS_MAX_THREADS=16
      - OPENPROJECT_WEB__WORKERS=4
    volumes:
      - openproject_assets:/var/openproject/assets
      - openproject_uploads:/var/openproject/files
    depends_on:
      openproject-db:
        condition: service_healthy
      openproject-cache:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health_checks/default"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nextcloud:
  nextcloud_data:
  db:
  onlyoffice_data:
  onlyoffice_logs:
  onlyoffice_cache:
  openproject_pgdata:
  openproject_assets:
  openproject_uploads: