services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.upturn.com.bd
      - OVERWRITECONDADDR=^172\..*$
      - TRUSTED_PROXIES=172.16.0.0/12 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 104.16.0.0/13 104.24.0.0/14 172.64.0.0/13 131.0.72.0/22
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  openproject-db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=${OPENPROJECT_DB_PASSWORD:-openproject123}
      - POSTGRES_DB=openproject
      - POSTGRES_USER=openproject
    volumes:
      - openproject_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openproject -d openproject"]
      interval: 10s
      timeout: 5s
      retries: 5

  openproject:
    image: openproject/community:13
    restart: always
    ports:
      - 8081:80
    environment:
      - OPENPROJECT_SECRET_KEY_BASE=${OPENPROJECT_SECRET_KEY_BASE:-supersecretkey123456789}
      - OPENPROJECT_HOST__NAME=${OPENPROJECT_DOMAIN_NAME:-localhost:8081}
      - OPENPROJECT_HTTPS=false
      - OPENPROJECT_SERVER__NAME=${OPENPROJECT_DOMAIN_NAME:-localhost:8081}
      - OPENPROJECT_RAILS__FORCE__SSL=false
      - OPENPROJECT_RAILS__RELATIVE__URL__ROOT=""
      - OPENPROJECT_WEB__TIMEOUT=120
      - OPENPROJECT_WEB__WORKER__TIMEOUT=120
      - OPENPROJECT_SESSION__STORE=active_record_store
      - OPENPROJECT_SESSION__COOKIE__NAME=_open_project_session
      - OPENPROJECT_CACHE__MEMCACHE__SERVER=localhost:11211
      - OPENPROJECT_CACHE__NAMESPACE=openproject
      - OPENPROJECT_SESSION__COOKIE__SAME__SITE=Lax
      - OPENPROJECT_SESSION__COOKIE__SECURE=false
      - DATABASE_URL=postgres://openproject:${OPENPROJECT_DB_PASSWORD:-openproject123}@openproject-db:5432/openproject
    volumes:
      - openproject_assets:/var/openproject/assets
      - openproject_uploads:/var/openproject/files
    depends_on:
      openproject-db:
        condition: service_healthy

volumes:
  nextcloud:
  nextcloud_data:
  db:
  openproject_pgdata:
  openproject_assets:
  openproject_uploads: