services:
  db:
    image: postgres:alpine
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud_password
    networks:
      - nextcloud

  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud_password
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin123
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.upturn.com.bd localhost
    depends_on:
      - db
    networks:
      - nextcloud

volumes:
  nextcloud_data:
  db_data:

networks:
  nextcloud:
